#!/usr/bin/env bun
/**
 * Generate Blog Index at Build Time
 *
 * This script reads all MDX files in src/content/blog/, parses their
 * frontmatter with gray-matter, and generates a TypeScript index file
 * that exports all post data.
 *
 * Run: bun run scripts/generate-blog-index.ts
 */

import { execFileSync } from 'node:child_process'
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import matter from 'gray-matter'

const contentDir = resolve(process.cwd(), 'src', 'content', 'blog')
const outputPath = resolve(contentDir, '_index.ts')

interface BlogPostData {
  title: string
  slug: string
  excerpt?: string
  featuredImage?: string
  category?: string
  authorName: string
  status: 'draft' | 'published' | 'scheduled'
  publishedAt?: string
  modifiedAt: string
  seo?: {
    metaTitle?: string
    metaDescription?: string
    ogImage?: string
    noindex?: boolean
  }
  content: string
}

/**
 * Main index generation function
 */
function generateBlogIndex() {
  console.log('📚 Generating blog index...')
  console.log(`   Content directory: ${contentDir}`)

  // Read all MDX files
  const files = readdirSync(contentDir).filter(
    (file) => file.endsWith('.mdx') && !file.startsWith('_')
  )

  console.log(`   Found ${files.length} MDX files`)

  const posts: BlogPostData[] = []

  for (const file of files) {
    const filepath = resolve(contentDir, file)
    const fileContent = readFileSync(filepath, 'utf-8')

    try {
      const { data, content } = matter(fileContent)

      const post: BlogPostData = {
        title: data.title || 'Untitled',
        slug: data.slug || file.replace('.mdx', ''),
        excerpt: data.excerpt,
        featuredImage: data.featuredImage,
        category: data.category,
        authorName: data.authorName || 'One Percent Digital',
        status: data.status || 'draft',
        publishedAt: data.publishedAt,
        modifiedAt: data.modifiedAt || new Date().toISOString(),
        seo: data.seo,
        content: content.trim(),
      }

      posts.push(post)
      console.log(`   ✅ ${file}`)
    } catch (error) {
      console.error(`   ❌ Error parsing ${file}:`, error)
    }
  }

  // Sort by publishedAt (newest first), then by modifiedAt
  posts.sort((a, b) => {
    const dateA = a.publishedAt
      ? new Date(a.publishedAt).getTime()
      : new Date(a.modifiedAt).getTime()
    const dateB = b.publishedAt
      ? new Date(b.publishedAt).getTime()
      : new Date(b.modifiedAt).getTime()
    return dateB - dateA
  })

  // Generate the TypeScript file
  const output = `/**
 * Blog Post Index
 *
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: bun run scripts/generate-blog-index.ts
 * Generated at: ${new Date().toISOString()}
 *
 * This file contains all blog posts with their frontmatter and content.
 * To add or modify posts, edit the MDX files in src/content/blog/
 * and re-run the generation script.
 */

import type { BlogPost } from '@/types/blog'

export const posts: BlogPost[] = ${JSON.stringify(posts, null, 2)}
`

  writeFileSync(outputPath, output, 'utf-8')

  // Format the generated file with Biome
  execFileSync('bunx', ['biome', 'format', '--write', outputPath], {
    stdio: 'pipe',
  })

  console.log(`\n📊 Index generated!`)
  console.log(`   Output: ${outputPath}`)
  console.log(`   Total posts: ${posts.length}`)
  console.log(
    `   Published: ${posts.filter((p) => p.status === 'published').length}`
  )
  console.log(`   Drafts: ${posts.filter((p) => p.status === 'draft').length}`)
}

// Run generation
try {
  generateBlogIndex()
} catch (error) {
  console.error('❌ Index generation failed:', error)
  process.exit(1)
}
