/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as GeoRouteImport } from './routes/geo'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SolutionsTechnologyRouteImport } from './routes/solutions.technology'
import { Route as SolutionsManufacturingRouteImport } from './routes/solutions.manufacturing'
import { Route as SolutionsLogisticsRouteImport } from './routes/solutions.logistics'
import { Route as SolutionsHospitalityRouteImport } from './routes/solutions.hospitality'
import { Route as SolutionsHealthWellnessRouteImport } from './routes/solutions.health-wellness'
import { Route as SolutionsEcommerceRouteImport } from './routes/solutions.ecommerce'
import { Route as SolutionsConsultingCoachingRouteImport } from './routes/solutions.consulting-coaching'
import { Route as SolutionsConstructionRouteImport } from './routes/solutions.construction'
import { Route as SolutionsAutomotiveRouteImport } from './routes/solutions.automotive'
import { Route as SolutionsAgricultureRouteImport } from './routes/solutions.agriculture'

const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoRoute = GeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsTechnologyRoute = SolutionsTechnologyRouteImport.update({
  id: '/solutions/technology',
  path: '/solutions/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsManufacturingRoute = SolutionsManufacturingRouteImport.update({
  id: '/solutions/manufacturing',
  path: '/solutions/manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsLogisticsRoute = SolutionsLogisticsRouteImport.update({
  id: '/solutions/logistics',
  path: '/solutions/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsHospitalityRoute = SolutionsHospitalityRouteImport.update({
  id: '/solutions/hospitality',
  path: '/solutions/hospitality',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsHealthWellnessRoute = SolutionsHealthWellnessRouteImport.update({
  id: '/solutions/health-wellness',
  path: '/solutions/health-wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsEcommerceRoute = SolutionsEcommerceRouteImport.update({
  id: '/solutions/ecommerce',
  path: '/solutions/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsConsultingCoachingRoute =
  SolutionsConsultingCoachingRouteImport.update({
    id: '/solutions/consulting-coaching',
    path: '/solutions/consulting-coaching',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsConstructionRoute = SolutionsConstructionRouteImport.update({
  id: '/solutions/construction',
  path: '/solutions/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsAutomotiveRoute = SolutionsAutomotiveRouteImport.update({
  id: '/solutions/automotive',
  path: '/solutions/automotive',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsAgricultureRoute = SolutionsAgricultureRouteImport.update({
  id: '/solutions/agriculture',
  path: '/solutions/agriculture',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/case-studies': typeof CaseStudiesRoute
  '/customers': typeof CustomersRoute
  '/enterprise': typeof EnterpriseRoute
  '/geo': typeof GeoRoute
  '/seo': typeof SeoRoute
  '/solutions/agriculture': typeof SolutionsAgricultureRoute
  '/solutions/automotive': typeof SolutionsAutomotiveRoute
  '/solutions/construction': typeof SolutionsConstructionRoute
  '/solutions/consulting-coaching': typeof SolutionsConsultingCoachingRoute
  '/solutions/ecommerce': typeof SolutionsEcommerceRoute
  '/solutions/health-wellness': typeof SolutionsHealthWellnessRoute
  '/solutions/hospitality': typeof SolutionsHospitalityRoute
  '/solutions/logistics': typeof SolutionsLogisticsRoute
  '/solutions/manufacturing': typeof SolutionsManufacturingRoute
  '/solutions/technology': typeof SolutionsTechnologyRoute
  '/blog': typeof BlogIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/case-studies': typeof CaseStudiesRoute
  '/customers': typeof CustomersRoute
  '/enterprise': typeof EnterpriseRoute
  '/geo': typeof GeoRoute
  '/seo': typeof SeoRoute
  '/solutions/agriculture': typeof SolutionsAgricultureRoute
  '/solutions/automotive': typeof SolutionsAutomotiveRoute
  '/solutions/construction': typeof SolutionsConstructionRoute
  '/solutions/consulting-coaching': typeof SolutionsConsultingCoachingRoute
  '/solutions/ecommerce': typeof SolutionsEcommerceRoute
  '/solutions/health-wellness': typeof SolutionsHealthWellnessRoute
  '/solutions/hospitality': typeof SolutionsHospitalityRoute
  '/solutions/logistics': typeof SolutionsLogisticsRoute
  '/solutions/manufacturing': typeof SolutionsManufacturingRoute
  '/solutions/technology': typeof SolutionsTechnologyRoute
  '/blog': typeof BlogIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/case-studies': typeof CaseStudiesRoute
  '/customers': typeof CustomersRoute
  '/enterprise': typeof EnterpriseRoute
  '/geo': typeof GeoRoute
  '/seo': typeof SeoRoute
  '/solutions/agriculture': typeof SolutionsAgricultureRoute
  '/solutions/automotive': typeof SolutionsAutomotiveRoute
  '/solutions/construction': typeof SolutionsConstructionRoute
  '/solutions/consulting-coaching': typeof SolutionsConsultingCoachingRoute
  '/solutions/ecommerce': typeof SolutionsEcommerceRoute
  '/solutions/health-wellness': typeof SolutionsHealthWellnessRoute
  '/solutions/hospitality': typeof SolutionsHospitalityRoute
  '/solutions/logistics': typeof SolutionsLogisticsRoute
  '/solutions/manufacturing': typeof SolutionsManufacturingRoute
  '/solutions/technology': typeof SolutionsTechnologyRoute
  '/blog/': typeof BlogIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/audit'
    | '/case-studies'
    | '/customers'
    | '/enterprise'
    | '/geo'
    | '/seo'
    | '/solutions/agriculture'
    | '/solutions/automotive'
    | '/solutions/construction'
    | '/solutions/consulting-coaching'
    | '/solutions/ecommerce'
    | '/solutions/health-wellness'
    | '/solutions/hospitality'
    | '/solutions/logistics'
    | '/solutions/manufacturing'
    | '/solutions/technology'
    | '/blog'
    | '/solutions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/audit'
    | '/case-studies'
    | '/customers'
    | '/enterprise'
    | '/geo'
    | '/seo'
    | '/solutions/agriculture'
    | '/solutions/automotive'
    | '/solutions/construction'
    | '/solutions/consulting-coaching'
    | '/solutions/ecommerce'
    | '/solutions/health-wellness'
    | '/solutions/hospitality'
    | '/solutions/logistics'
    | '/solutions/manufacturing'
    | '/solutions/technology'
    | '/blog'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/audit'
    | '/case-studies'
    | '/customers'
    | '/enterprise'
    | '/geo'
    | '/seo'
    | '/solutions/agriculture'
    | '/solutions/automotive'
    | '/solutions/construction'
    | '/solutions/consulting-coaching'
    | '/solutions/ecommerce'
    | '/solutions/health-wellness'
    | '/solutions/hospitality'
    | '/solutions/logistics'
    | '/solutions/manufacturing'
    | '/solutions/technology'
    | '/blog/'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuditRoute: typeof AuditRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  CustomersRoute: typeof CustomersRoute
  EnterpriseRoute: typeof EnterpriseRoute
  GeoRoute: typeof GeoRoute
  SeoRoute: typeof SeoRoute
  SolutionsAgricultureRoute: typeof SolutionsAgricultureRoute
  SolutionsAutomotiveRoute: typeof SolutionsAutomotiveRoute
  SolutionsConstructionRoute: typeof SolutionsConstructionRoute
  SolutionsConsultingCoachingRoute: typeof SolutionsConsultingCoachingRoute
  SolutionsEcommerceRoute: typeof SolutionsEcommerceRoute
  SolutionsHealthWellnessRoute: typeof SolutionsHealthWellnessRoute
  SolutionsHospitalityRoute: typeof SolutionsHospitalityRoute
  SolutionsLogisticsRoute: typeof SolutionsLogisticsRoute
  SolutionsManufacturingRoute: typeof SolutionsManufacturingRoute
  SolutionsTechnologyRoute: typeof SolutionsTechnologyRoute
  BlogIndexRoute: typeof BlogIndexRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo': {
      id: '/geo'
      path: '/geo'
      fullPath: '/geo'
      preLoaderRoute: typeof GeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/technology': {
      id: '/solutions/technology'
      path: '/solutions/technology'
      fullPath: '/solutions/technology'
      preLoaderRoute: typeof SolutionsTechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/manufacturing': {
      id: '/solutions/manufacturing'
      path: '/solutions/manufacturing'
      fullPath: '/solutions/manufacturing'
      preLoaderRoute: typeof SolutionsManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/logistics': {
      id: '/solutions/logistics'
      path: '/solutions/logistics'
      fullPath: '/solutions/logistics'
      preLoaderRoute: typeof SolutionsLogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/hospitality': {
      id: '/solutions/hospitality'
      path: '/solutions/hospitality'
      fullPath: '/solutions/hospitality'
      preLoaderRoute: typeof SolutionsHospitalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/health-wellness': {
      id: '/solutions/health-wellness'
      path: '/solutions/health-wellness'
      fullPath: '/solutions/health-wellness'
      preLoaderRoute: typeof SolutionsHealthWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/ecommerce': {
      id: '/solutions/ecommerce'
      path: '/solutions/ecommerce'
      fullPath: '/solutions/ecommerce'
      preLoaderRoute: typeof SolutionsEcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/consulting-coaching': {
      id: '/solutions/consulting-coaching'
      path: '/solutions/consulting-coaching'
      fullPath: '/solutions/consulting-coaching'
      preLoaderRoute: typeof SolutionsConsultingCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/construction': {
      id: '/solutions/construction'
      path: '/solutions/construction'
      fullPath: '/solutions/construction'
      preLoaderRoute: typeof SolutionsConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/automotive': {
      id: '/solutions/automotive'
      path: '/solutions/automotive'
      fullPath: '/solutions/automotive'
      preLoaderRoute: typeof SolutionsAutomotiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/agriculture': {
      id: '/solutions/agriculture'
      path: '/solutions/agriculture'
      fullPath: '/solutions/agriculture'
      preLoaderRoute: typeof SolutionsAgricultureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuditRoute: AuditRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  CustomersRoute: CustomersRoute,
  EnterpriseRoute: EnterpriseRoute,
  GeoRoute: GeoRoute,
  SeoRoute: SeoRoute,
  SolutionsAgricultureRoute: SolutionsAgricultureRoute,
  SolutionsAutomotiveRoute: SolutionsAutomotiveRoute,
  SolutionsConstructionRoute: SolutionsConstructionRoute,
  SolutionsConsultingCoachingRoute: SolutionsConsultingCoachingRoute,
  SolutionsEcommerceRoute: SolutionsEcommerceRoute,
  SolutionsHealthWellnessRoute: SolutionsHealthWellnessRoute,
  SolutionsHospitalityRoute: SolutionsHospitalityRoute,
  SolutionsLogisticsRoute: SolutionsLogisticsRoute,
  SolutionsManufacturingRoute: SolutionsManufacturingRoute,
  SolutionsTechnologyRoute: SolutionsTechnologyRoute,
  BlogIndexRoute: BlogIndexRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
