/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as GeoRouteImport } from './routes/geo'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SolutionsTechnologyRouteImport } from './routes/solutions.technology'
import { Route as SolutionsRealEstateRouteImport } from './routes/solutions.real-estate'
import { Route as SolutionsManufacturingRouteImport } from './routes/solutions.manufacturing'
import { Route as SolutionsLogisticsRouteImport } from './routes/solutions.logistics'
import { Route as SolutionsLegalRouteImport } from './routes/solutions.legal'
import { Route as SolutionsHospitalityRouteImport } from './routes/solutions.hospitality'
import { Route as SolutionsHealthWellnessRouteImport } from './routes/solutions.health-wellness'
import { Route as SolutionsFinanceInsuranceRouteImport } from './routes/solutions.finance-insurance'
import { Route as SolutionsEcommerceRouteImport } from './routes/solutions.ecommerce'
import { Route as SolutionsConstructionRouteImport } from './routes/solutions.construction'
import { Route as SolutionsAutomotiveRouteImport } from './routes/solutions.automotive'
import { Route as SolutionsAgricultureRouteImport } from './routes/solutions.agriculture'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoRoute = GeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsTechnologyRoute = SolutionsTechnologyRouteImport.update({
  id: '/solutions/technology',
  path: '/solutions/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRealEstateRoute = SolutionsRealEstateRouteImport.update({
  id: '/solutions/real-estate',
  path: '/solutions/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsManufacturingRoute = SolutionsManufacturingRouteImport.update({
  id: '/solutions/manufacturing',
  path: '/solutions/manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsLogisticsRoute = SolutionsLogisticsRouteImport.update({
  id: '/solutions/logistics',
  path: '/solutions/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsLegalRoute = SolutionsLegalRouteImport.update({
  id: '/solutions/legal',
  path: '/solutions/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsHospitalityRoute = SolutionsHospitalityRouteImport.update({
  id: '/solutions/hospitality',
  path: '/solutions/hospitality',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsHealthWellnessRoute = SolutionsHealthWellnessRouteImport.update({
  id: '/solutions/health-wellness',
  path: '/solutions/health-wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsFinanceInsuranceRoute =
  SolutionsFinanceInsuranceRouteImport.update({
    id: '/solutions/finance-insurance',
    path: '/solutions/finance-insurance',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsEcommerceRoute = SolutionsEcommerceRouteImport.update({
  id: '/solutions/ecommerce',
  path: '/solutions/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsConstructionRoute = SolutionsConstructionRouteImport.update({
  id: '/solutions/construction',
  path: '/solutions/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsAutomotiveRoute = SolutionsAutomotiveRouteImport.update({
  id: '/solutions/automotive',
  path: '/solutions/automotive',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsAgricultureRoute = SolutionsAgricultureRouteImport.update({
  id: '/solutions/agriculture',
  path: '/solutions/agriculture',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/case-studies': typeof CaseStudiesRoute
  '/customers': typeof CustomersRoute
  '/enterprise': typeof EnterpriseRoute
  '/geo': typeof GeoRoute
  '/seo': typeof SeoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/solutions/agriculture': typeof SolutionsAgricultureRoute
  '/solutions/automotive': typeof SolutionsAutomotiveRoute
  '/solutions/construction': typeof SolutionsConstructionRoute
  '/solutions/ecommerce': typeof SolutionsEcommerceRoute
  '/solutions/finance-insurance': typeof SolutionsFinanceInsuranceRoute
  '/solutions/health-wellness': typeof SolutionsHealthWellnessRoute
  '/solutions/hospitality': typeof SolutionsHospitalityRoute
  '/solutions/legal': typeof SolutionsLegalRoute
  '/solutions/logistics': typeof SolutionsLogisticsRoute
  '/solutions/manufacturing': typeof SolutionsManufacturingRoute
  '/solutions/real-estate': typeof SolutionsRealEstateRoute
  '/solutions/technology': typeof SolutionsTechnologyRoute
  '/blog': typeof BlogIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/case-studies': typeof CaseStudiesRoute
  '/customers': typeof CustomersRoute
  '/enterprise': typeof EnterpriseRoute
  '/geo': typeof GeoRoute
  '/seo': typeof SeoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/solutions/agriculture': typeof SolutionsAgricultureRoute
  '/solutions/automotive': typeof SolutionsAutomotiveRoute
  '/solutions/construction': typeof SolutionsConstructionRoute
  '/solutions/ecommerce': typeof SolutionsEcommerceRoute
  '/solutions/finance-insurance': typeof SolutionsFinanceInsuranceRoute
  '/solutions/health-wellness': typeof SolutionsHealthWellnessRoute
  '/solutions/hospitality': typeof SolutionsHospitalityRoute
  '/solutions/legal': typeof SolutionsLegalRoute
  '/solutions/logistics': typeof SolutionsLogisticsRoute
  '/solutions/manufacturing': typeof SolutionsManufacturingRoute
  '/solutions/real-estate': typeof SolutionsRealEstateRoute
  '/solutions/technology': typeof SolutionsTechnologyRoute
  '/blog': typeof BlogIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/case-studies': typeof CaseStudiesRoute
  '/customers': typeof CustomersRoute
  '/enterprise': typeof EnterpriseRoute
  '/geo': typeof GeoRoute
  '/seo': typeof SeoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/solutions/agriculture': typeof SolutionsAgricultureRoute
  '/solutions/automotive': typeof SolutionsAutomotiveRoute
  '/solutions/construction': typeof SolutionsConstructionRoute
  '/solutions/ecommerce': typeof SolutionsEcommerceRoute
  '/solutions/finance-insurance': typeof SolutionsFinanceInsuranceRoute
  '/solutions/health-wellness': typeof SolutionsHealthWellnessRoute
  '/solutions/hospitality': typeof SolutionsHospitalityRoute
  '/solutions/legal': typeof SolutionsLegalRoute
  '/solutions/logistics': typeof SolutionsLogisticsRoute
  '/solutions/manufacturing': typeof SolutionsManufacturingRoute
  '/solutions/real-estate': typeof SolutionsRealEstateRoute
  '/solutions/technology': typeof SolutionsTechnologyRoute
  '/blog/': typeof BlogIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apply'
    | '/case-studies'
    | '/customers'
    | '/enterprise'
    | '/geo'
    | '/seo'
    | '/blog/$slug'
    | '/solutions/agriculture'
    | '/solutions/automotive'
    | '/solutions/construction'
    | '/solutions/ecommerce'
    | '/solutions/finance-insurance'
    | '/solutions/health-wellness'
    | '/solutions/hospitality'
    | '/solutions/legal'
    | '/solutions/logistics'
    | '/solutions/manufacturing'
    | '/solutions/real-estate'
    | '/solutions/technology'
    | '/blog'
    | '/solutions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/case-studies'
    | '/customers'
    | '/enterprise'
    | '/geo'
    | '/seo'
    | '/blog/$slug'
    | '/solutions/agriculture'
    | '/solutions/automotive'
    | '/solutions/construction'
    | '/solutions/ecommerce'
    | '/solutions/finance-insurance'
    | '/solutions/health-wellness'
    | '/solutions/hospitality'
    | '/solutions/legal'
    | '/solutions/logistics'
    | '/solutions/manufacturing'
    | '/solutions/real-estate'
    | '/solutions/technology'
    | '/blog'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apply'
    | '/case-studies'
    | '/customers'
    | '/enterprise'
    | '/geo'
    | '/seo'
    | '/blog/$slug'
    | '/solutions/agriculture'
    | '/solutions/automotive'
    | '/solutions/construction'
    | '/solutions/ecommerce'
    | '/solutions/finance-insurance'
    | '/solutions/health-wellness'
    | '/solutions/hospitality'
    | '/solutions/legal'
    | '/solutions/logistics'
    | '/solutions/manufacturing'
    | '/solutions/real-estate'
    | '/solutions/technology'
    | '/blog/'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplyRoute: typeof ApplyRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  CustomersRoute: typeof CustomersRoute
  EnterpriseRoute: typeof EnterpriseRoute
  GeoRoute: typeof GeoRoute
  SeoRoute: typeof SeoRoute
  BlogSlugRoute: typeof BlogSlugRoute
  SolutionsAgricultureRoute: typeof SolutionsAgricultureRoute
  SolutionsAutomotiveRoute: typeof SolutionsAutomotiveRoute
  SolutionsConstructionRoute: typeof SolutionsConstructionRoute
  SolutionsEcommerceRoute: typeof SolutionsEcommerceRoute
  SolutionsFinanceInsuranceRoute: typeof SolutionsFinanceInsuranceRoute
  SolutionsHealthWellnessRoute: typeof SolutionsHealthWellnessRoute
  SolutionsHospitalityRoute: typeof SolutionsHospitalityRoute
  SolutionsLegalRoute: typeof SolutionsLegalRoute
  SolutionsLogisticsRoute: typeof SolutionsLogisticsRoute
  SolutionsManufacturingRoute: typeof SolutionsManufacturingRoute
  SolutionsRealEstateRoute: typeof SolutionsRealEstateRoute
  SolutionsTechnologyRoute: typeof SolutionsTechnologyRoute
  BlogIndexRoute: typeof BlogIndexRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo': {
      id: '/geo'
      path: '/geo'
      fullPath: '/geo'
      preLoaderRoute: typeof GeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/technology': {
      id: '/solutions/technology'
      path: '/solutions/technology'
      fullPath: '/solutions/technology'
      preLoaderRoute: typeof SolutionsTechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/real-estate': {
      id: '/solutions/real-estate'
      path: '/solutions/real-estate'
      fullPath: '/solutions/real-estate'
      preLoaderRoute: typeof SolutionsRealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/manufacturing': {
      id: '/solutions/manufacturing'
      path: '/solutions/manufacturing'
      fullPath: '/solutions/manufacturing'
      preLoaderRoute: typeof SolutionsManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/logistics': {
      id: '/solutions/logistics'
      path: '/solutions/logistics'
      fullPath: '/solutions/logistics'
      preLoaderRoute: typeof SolutionsLogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/legal': {
      id: '/solutions/legal'
      path: '/solutions/legal'
      fullPath: '/solutions/legal'
      preLoaderRoute: typeof SolutionsLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/hospitality': {
      id: '/solutions/hospitality'
      path: '/solutions/hospitality'
      fullPath: '/solutions/hospitality'
      preLoaderRoute: typeof SolutionsHospitalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/health-wellness': {
      id: '/solutions/health-wellness'
      path: '/solutions/health-wellness'
      fullPath: '/solutions/health-wellness'
      preLoaderRoute: typeof SolutionsHealthWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/finance-insurance': {
      id: '/solutions/finance-insurance'
      path: '/solutions/finance-insurance'
      fullPath: '/solutions/finance-insurance'
      preLoaderRoute: typeof SolutionsFinanceInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/ecommerce': {
      id: '/solutions/ecommerce'
      path: '/solutions/ecommerce'
      fullPath: '/solutions/ecommerce'
      preLoaderRoute: typeof SolutionsEcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/construction': {
      id: '/solutions/construction'
      path: '/solutions/construction'
      fullPath: '/solutions/construction'
      preLoaderRoute: typeof SolutionsConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/automotive': {
      id: '/solutions/automotive'
      path: '/solutions/automotive'
      fullPath: '/solutions/automotive'
      preLoaderRoute: typeof SolutionsAutomotiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/agriculture': {
      id: '/solutions/agriculture'
      path: '/solutions/agriculture'
      fullPath: '/solutions/agriculture'
      preLoaderRoute: typeof SolutionsAgricultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplyRoute: ApplyRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  CustomersRoute: CustomersRoute,
  EnterpriseRoute: EnterpriseRoute,
  GeoRoute: GeoRoute,
  SeoRoute: SeoRoute,
  BlogSlugRoute: BlogSlugRoute,
  SolutionsAgricultureRoute: SolutionsAgricultureRoute,
  SolutionsAutomotiveRoute: SolutionsAutomotiveRoute,
  SolutionsConstructionRoute: SolutionsConstructionRoute,
  SolutionsEcommerceRoute: SolutionsEcommerceRoute,
  SolutionsFinanceInsuranceRoute: SolutionsFinanceInsuranceRoute,
  SolutionsHealthWellnessRoute: SolutionsHealthWellnessRoute,
  SolutionsHospitalityRoute: SolutionsHospitalityRoute,
  SolutionsLegalRoute: SolutionsLegalRoute,
  SolutionsLogisticsRoute: SolutionsLogisticsRoute,
  SolutionsManufacturingRoute: SolutionsManufacturingRoute,
  SolutionsRealEstateRoute: SolutionsRealEstateRoute,
  SolutionsTechnologyRoute: SolutionsTechnologyRoute,
  BlogIndexRoute: BlogIndexRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
